// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://byuumsdspsffxaprgfsh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5dXVtc2RzcHNmZnhhcHJnZnNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3NDQ5MTcsImV4cCI6MjA2NTMyMDkxN30.tICPFIioN5AH-vzdGSQzbWIAFQnEEtFbW1Oasg_HzTY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);